server:
  port: 443
  ssl:
    certificate: "{{bst_mount_dir}}/environment/ssl/localhost.crt"
    certificate-private-key: "{{bst_mount_dir}}/environment/ssl/localhost.key"
    trust-certificate: "{{bst_mount_dir}}/environment/ssl/localhost.crt"

spring:
  jpa:
    database-platform : org.hibernate.dialect.PostgreSQLDialect
    properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://{{db_host}}:{{db_port}}/{{db_name}}"
    username: "{{db_user}}"
    password: "{{db_password}}"
