settings:
  container-prefix: "bst-"
  jmetr-source: "https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.4.3.zip"

storages:
  db-postgres:
    title: "PostgreSQL v14.1"
    container: "db-postgres"
    start-delay: 12

solutions:
  go-beego:
    title: "Go Beego v2.0.2"
    container: "go-beego"
  java-spring:
    title: "Java Spring v2.7.1 (Netty)"
    container: "java-spring"
  php-symfony:
    title: "PHP Symfony v6.0 (Nginx)"
    container: "php-symfony"
  python-django:
    title: "Python Django v4.0.3 (Daphne, async)"
    container: "python-django"

test-plan:
  index:
    title: "Get JSON"
    run: true
    jmx: "environment/test-plan/index.jmx"
    ready-check: "https://localhost"
    solutions:
      - go-beego
      - java-spring
      - php-symfony
      - python-django
  index_stress:
    title: "Get JSON stress, until first error (max response/request time 10sec)"
    run: true
    jmx: "environment/test-plan/index_stress.jmx"
    ready-check: "https://localhost"
    solutions:
      - go-beego
      - java-spring
      - php-symfony
      - python-django
  get_entity:
    title: "Get JSON using DB PostgreSQL (ORM)"
    run: true
    jmx: "environment/test-plan/get_entity.jmx"
    setup: "environment/test-plan/setup/get_entity.py"
    ready-check: "https://localhost"
    storages:
      - db-postgres
    solutions:
      - go-beego
      - java-spring
      - php-symfony
      - python-django
  get_entity_stress:
    title: "Get JSON using DB PostgreSQL (ORM) stress, until first error (max response/request time 10sec)"
    run: true
    jmx: "environment/test-plan/get_entity_stress.jmx"
    setup: "environment/test-plan/setup/get_entity.py"
    ready-check: "https://localhost"
    storages:
      - db-postgres
    solutions:
      - go-beego
      - java-spring
      - php-symfony
      - python-django
  add_entity:
    title: "Insert to DB PostgreSQL (ORM)"
    run: true
    jmx: "environment/test-plan/add_entity.jmx"
    setup: "environment/test-plan/setup/add_entity.py"
    ready-check: "https://localhost"
    storages:
      - db-postgres
    solutions:
      - go-beego
      - java-spring
      - php-symfony
      - python-django
  add_entity_stress:
    title: "Insert to DB PostgreSQL (ORM) stress, until first error (max response/request time 10sec)"
    run: true
    jmx: "environment/test-plan/add_entity_stress.jmx"
    setup: "environment/test-plan/setup/add_entity.py"
    ready-check: "https://localhost"
    storages:
      - db-postgres
    solutions:
      - go-beego
      - java-spring
      - php-symfony
      - python-django
  fibonacci_recursive:
    title: "Fibonacci number calculation recursive"
    run: true
    jmx: "environment/test-plan/fibonacci_recursive.jmx"
    setup: "environment/test-plan/setup/fibonacci_recursive.py"
    ready-check: "https://localhost"
    solutions:
      - go-beego
      - java-spring
      - php-symfony
      - python-django
  cycle_sum:
    title: "Iterative sum calculation cycle"
    run: true
    jmx: "environment/test-plan/cycle_sum.jmx"
    setup: "environment/test-plan/setup/cycle_sum.py"
    ready-check: "https://localhost"
    solutions:
      - go-beego
      - java-spring
      - php-symfony
      - python-django
